camel:
  springboot:
    main-run-controller: true
api:
  source: file:///Users/luohuiqi/work/workspace/me/camel-scaffold/src/test/java/com/zdww/camel/source?noop=true
  destination: file:///Users/luohuiqi/work/workspace/me/camel-scaffold/src/test/java/com/zdww/camel/destination

