camel:
  springboot:
    main-run-controller: true
#api:
#  source: file:///Users/luohuiqi/work/workspace/me/camel-scaffold/ftp/src/test/java/com/auch/camel/ftp/source?noop=true
#  destination: file:///Users/luohuiqi/work/workspace/me/camel-scaffold/ftp/src/test/java/com/auch/camel/ftp/destination
server:
  port: 8866
